version: '3.1'

services:
  mongo:
    image: mongo
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d # Mount the init script folder to the MongoDB container
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: oneday
    ports:
      - "27017:27017"


  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpassword
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
  mongo-data:
